try {
    undefined();
}  catch (err) {
    console.log(err);
} 
console.log(err); // ReferenceError: err not found